spring:
  application:
    name: Ssak3
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL}
    properties:
      hibernate:
        format_sql: false
    show-sql: true
  jackson:
    time-zone: Asia/Seoul
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cache:
    cache-names: "categoryCache"
    caffeine:
      spec: "maximumSize=100,expireAfterAccess=600s"

jwt:
  secret:
    key: ${SECRET_KEY}

kakao:
  client_id: ${CLIENT_ID}
  redirect_uri: ${REDIRECT_URI}
  client_secret: ${CLIENT_SECRET}

toss:
  secret-key: ${TOSS_SECRET_KEY}

app:
  frontend:
    base-url: http://localhost:8080

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ${AWS_S3_REGION}
    stack:
      auto: false
